import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CRUD StairsDigital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-6xl mx-auto mt-6 text-black-800">
          <header className="p-6 border-b flex justify-around bg-red-500 rounded-tl-lg rounded-tr-lg text-2xl text-white font-bold">
            <Link href={'/'}>Itens</Link>
            <Link href={'/posts'}>Posts</Link>
          </header>
          <main className="text-lg" >
            {children}
          </main>
        </div>
        
      </body>
    </html>
  );
}
